### ISSUE TITLE
[Bug]: Error: Not connected - is it possible to make connection timeout configurable?

### ISSUE THREAD

**Issue by akramarev** [livecycle/preevy#519]
### What happened?

Please compare these two outputs from livecycle/preevy-up-action@v2.4.0:
```
Build step done in 716.21s
    Error: Not connected
Error: Process completed with exit code 1.
```
and
```
Build step done in 31.32s
- Copying files: Calculating...
✔ Copied 4 files to remote machine
Running: docker compose up -d --remove-orphans --no-build
- Connecting to remote docker socket...
✔ Connected to remote docker socket
```

The first one is a cold run of my workflow where the build stage took >10m, and succeeded, but artifacts copying failed right after it. The second output is from the same workflow retried - it reused cached images and thus build phase finished in 30s and preevy-up-action didn't have any problems with copying the artifacts to the runner.

I suspect that there is a timeout (ssh connection timeout) that approximately equals 10m somewhere. Wondering if it's possible to make it configurable for docker-compose stacks that require a longer build phase?

### Add screenshots

please see the previous section with error details

### Steps to reproduce the behavior

My setup:

* public tunnel server
* deploy runtime: AWS Lightsail
* a docker-compose with a service which build:context step takes a long time (10m)
* GHA with livecycle/preevy-up-action@v2.4.0 that uses GH builder and GHCR

GHA:
```
...
      - name: Set up Docker Buildx
        id: buildx_setup
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: livecycle/preevy-up-action@v2.4.0
        id: preevy
        with:
          install: gh-release
          profile-url: "${{ vars.PREEVY_PROFILE_URL }}"
          args: --registry ghcr.io/my-org --builder ${{ steps.buildx_setup.outputs.name }}
          docker-compose-yaml-paths: "./docker-compose.yml"
        env:
          GITHUB_TOKEN: ${{ github.token }}
```

### Expected behavior

Avoid `Error: Not connected` error when the build step takes a long time, i.e. either make the timeout configurable or retry the connection just a few times.

### What OS are you seeing the problem on?

Linux

### Record

- [X] I agree to follow this project's Code of Conduct
