### ISSUE TITLE
[Bug]: Cannot establish MongoDB connection

### ISSUE THREAD

**Issue by alextarana** [livecycle/preevy#522]
### What happened?

I am trying to deploy this:

```
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:
```

and it works well but I think that the tunnel doesn't support mongodb:// protocol and so I am not able to connect to the service.

### Add screenshots

No screenshot

### Steps to reproduce the behavior

Try to use the code above to reproduce the error.

### Expected behavior

Establish connection properly.

### Additional context

AWS Lightsail

### Record

- [X] I agree to follow this project's Code of Conduct
