### ISSUE TITLE
[Bug]: Running `preevy up` with services fails 

### ISSUE THREAD

**Issue by nhuray** [livecycle/preevy#533]
### What happened?

Running `preevy up` with SERVICES arg fails.

### Docker Compose file

<img width="597" alt="Screenshot 2024-08-05 at 10 13 39 PM" src="https://github.com/user-attachments/assets/5ce90caa-5a8b-4364-8744-cb1f81eecb7f">

### Running `preevy up`

<img width="1480" alt="Screenshot 2024-08-05 at 10 12 15 PM" src="https://github.com/user-attachments/assets/554d4c0f-8e4c-4787-956f-b332c3034a78">

Passing the service `wordpress` fails with error:

```
Error: command `docker compose --project-directory /Users/nicolas/Workspace/awesome-compose/wordpress-mysql -f compose.yaml convert wordpress preevy_proxy` exited with code 1: no such service: preevy_proxy
```

### Steps to reproduce the behavior

Copy the following docker compose file:

```yaml
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${PREEVY_BASE_URI_DB_3306:-db}
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

volumes:
  db_data:
```

Run `preevy up wordpress`

### Expected behavior

Specifying service(s) should deploy a preview environment with only these service(s) (and dependencies)

### What OS are you seeing the problem on?

MacOS

### Additional context

Preevy Version: 0.0.64
Deployed on Kubernetes

### Record

- [X] I agree to follow this project's Code of Conduct
