### ISSUE TITLE
Add environment variables for tunnel-server urls for usage in docker-compose

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#57]
When doing service-service communication, Preevy can work well due to compose service discovery.
However, when using a frontend that utilize the exposed port for connecting to backend (can be common in dev environments), it's a bit tricky since we need to replace the url with tunneling url which we don't know about yet.

One way to solve it, is by injecting/resolving env variables of tunneling url in compose normalization. (so it can affect both build args, and environment)

For example:
```yaml
services:
     api:
           ....
           ports:
           - 9005:3000
     fronend:
          environment:
          - API_URL=http://localhost:9005
```
This could be a common setup.

With Preevy, it could be something like:
```yaml
services:
     api:
           ....
           ports:
           - 9005:3000
     fronend:
          environment:
          - API_URL={PREEVY_BASE_URI_API_3000:-http://localhost:9005}
 ```
In the future, we can enhance this by supporting inference of this configuration automatically and replacing all static `http://localhost:xx` variables' values based on public ports definitions.
