### ISSUE TITLE
Suggestion: Create Action to ease the use of Preevy in GH actions

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#64]
**Is your feature request related to a problem? Please describe.**
An easy way to set up Preevy up/down flows in GH actions.
Currently, it requires installing Preevy with npm -g or using npx.

**Describe the solution you'd like**
A GH action that wrap the up/down parameters.
Profile is specified as parameter and importing is done automatically.

```
uses: preevy/action@v1
with:
     profile-url: "s3://aabcd"
     command: up
     args: 
```

**Describe alternatives you've considered**
It's possible to remove NPM dependency/installation by packing Preevy CLI as a Docker image, and support environment variable for profile URL, but there's a drawback which it's not trivial to get the cloud provider context when running this way.
